require "active_support/core_ext/integer/time"

Rails.application.configure do
  # Settings specified here will take precedence over those in config/application.rb.

  # Make code changes take effect immediately without server restart.
  config.enable_reloading = true

  # Do not eager load code on boot.
  config.eager_load = false

  # Show full error reports.
  config.consider_all_requests_local = true

  # Enable server timing.
  config.server_timing = true

  # Enable/disable Action Controller caching. By default Action Controller caching is disabled.
  # Run rails dev:cache to toggle Action Controller caching.
  if Rails.root.join("tmp/caching-dev.txt").exist?
    config.action_controller.perform_caching = true
    config.action_controller.enable_fragment_cache_logging = true
    # More aggressive caching for images and assets
    config.public_file_server.headers = { 
      "cache-control" => "public, max-age=#{7.days.to_i}",
      "expires" => 7.days.from_now.to_formatted_s(:rfc822)
    }
  else
    config.action_controller.perform_caching = false
  end

  # Change to :null_store to avoid any caching.
  config.cache_store = :memory_store

  # Store uploaded files on the local file system (see config/storage.yml for options).
  config.active_storage.service = :local
  
  # Active Storage optimized for development stability
  config.active_storage.variant_processor = :vips
  config.active_storage.resolve_model_to_route = :rails_storage_proxy
  # Disable preload hints for Active Storage in development to avoid CORS conflicts
  config.active_storage.precompile_assets = false

  # Don't care if the mailer can't send.
  config.action_mailer.raise_delivery_errors = false

  # Make template changes take effect immediately.
  config.action_mailer.perform_caching = false

  # Set localhost to be used by links generated in mailer templates.
  config.action_mailer.default_url_options = { host: "localhost", port: 3000 }

  # Print deprecation notices to the Rails logger.
  config.active_support.deprecation = :log

  # Raise an error on page load if there are pending migrations.
  config.active_record.migration_error = :page_load

  # Highlight code that triggered database queries in logs.
  config.active_record.verbose_query_logs = true

  # Append comments with runtime information tags to SQL queries in logs.
  config.active_record.query_log_tags_enabled = true

  # Highlight code that enqueued background job in logs.
  config.active_job.verbose_enqueue_logs = true

  # Raises error for missing translations.
  # config.i18n.raise_on_missing_translations = true

  # Annotate rendered view with file names.
  config.action_view.annotate_rendered_view_with_filenames = true

  # Uncomment if you wish to allow Action Cable access from any origin.
  # config.action_cable.disable_request_forgery_protection = true

  # Raise error when a before_action's only/except options reference missing actions.
  config.action_controller.raise_on_missing_callback_actions = true

  # Apply autocorrection by RuboCop to files generated by `bin/rails generate`.
  # config.generators.apply_rubocop_autocorrect_after_generate!
  
  # Enable performance profiling tools
  config.after_initialize do
    require 'rack-mini-profiler'
    # Memory usage tracking
    Rack::MiniProfiler.config.enable_advanced_debugging_tools = true
    
    # Only show profiler when URL has ?pp=help or similar
    # Remove this line to show profiler on every page
    Rack::MiniProfiler.config.authorization_mode = :allow_authorized
    
    # Hide profiler by default - show only with ?pp=help
    Rack::MiniProfiler.config.skip_schema_queries = true
    Rack::MiniProfiler.config.auto_inject = false
  end
end
